"""Create or update Django admin superuser and persist credentials to .env."""

from __future__ import annotations

import os
import pathlib
import re
import secrets
import string
import sys

import django

BASE = pathlib.Path(__file__).resolve().parents[1]
ROOT = BASE.parent
ENV_PATH = ROOT / ".env"
sys.path.insert(0, str(BASE))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "eldinia_nex.settings")

django.setup()

from django.contrib.auth import get_user_model  # noqa: E402

User = get_user_model()


def generate_password(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def upsert_env(path: pathlib.Path, updates: dict[str, str]) -> None:
    lines: list[str] = []
    if path.exists():
        lines = path.read_text(encoding="utf-8").splitlines()

    remaining = dict(updates)
    pattern = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=")

    for index, line in enumerate(lines):
        match = pattern.match(line)
        if not match:
            continue
        key = match.group(1)
        if key in remaining:
            lines[index] = f"{key}={remaining.pop(key)}"

    if remaining:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# Django Admin (local dev — auto-generated by create_superuser.py)")
        for key, value in remaining.items():
            lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    username = os.getenv("DJANGO_ADMIN_USERNAME", "eldonia_admin")
    email = os.getenv("DJANGO_ADMIN_EMAIL", "admin@eldonia-nex.local")
    password = os.getenv("DJANGO_ADMIN_PASSWORD") or generate_password()

    user, created = User.objects.get_or_create(
        username=username,
        defaults={"email": email},
    )
    user.email = email
    user.is_staff = True
    user.is_superuser = True
    user.is_active = True
    if hasattr(user, "is_email_verified"):
        user.is_email_verified = True
    user.set_password(password)
    user.save()

    if os.getenv("SKIP_ENV_WRITE", "").lower() != "true":
        try:
            upsert_env(
                ENV_PATH,
                {
                    "DJANGO_ADMIN_USERNAME": username,
                    "DJANGO_ADMIN_EMAIL": email,
                    "DJANGO_ADMIN_PASSWORD": password,
                    "DJANGO_ADMIN_URL": "http://localhost:8000/admin/",
                },
            )
            print(f"Credentials saved to: {ENV_PATH}")
        except OSError as exc:
            print(f"Skipped .env write ({exc})")

    action = "created" if created else "updated"
    print(f"Superuser {action}: {username} <{email}>")
    print(f"Admin URL: /admin/")
    print(f"DJANGO_ADMIN_USERNAME={username}")
    if os.getenv("PRINT_ADMIN_PASSWORD", "true").lower() == "true":
        print(f"DJANGO_ADMIN_PASSWORD={password}")


if __name__ == "__main__":
    main()
