# Generated by Django 5.2.3 on 2026-01-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for the setting (e.g., 'SITE_NAME')", max_length=100, unique=True)),
                ('value', models.JSONField(help_text="The actual value of the setting, stored as JSON (e.g., 'Eldonia Nex', true, 100).")),
                ('category', models.CharField(choices=[('SITE', 'Site Settings'), ('SECURITY', 'Security Settings'), ('FEATURES', 'Feature Flags'), ('MAINTENANCE', 'Maintenance'), ('SYSTEM', 'System Internals')], default='SITE', max_length=20)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('JSON', 'JSON')], default='STRING', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Explanation of what this setting controls.')),
                ('is_public', models.BooleanField(default=False, help_text='If true, this setting can be read by public API endpoints.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'core_system_settings',
            },
        ),
    ]
