# Generated by Django 5.2.3 on 2026-01-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('SITE', 'Site Settings'), ('SECURITY', 'Security'), ('FEATURES', 'Feature Flags'), ('MAINTENANCE', 'Maintenance'), ('SYSTEM', 'System Health'), ('GAMIFICATION', 'Gamification (EXP)'), ('FINANCE', 'Finance & Fees'), ('CONTENT', 'Content & UI')], default='SITE', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('FLOAT', 'Float'), ('JSON', 'JSON/List')], default='STRING', max_length=10),
        ),
    ]
