# Generated by Django 5.2.3 on 2026-01-01 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_settings', '0002_alter_systemsetting_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL slug for the page (e.g., 'about-us')", max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Markdown or HTML content of the page')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ALERT', 'Alert/Danger')], default='INFO', max_length=10)),
                ('criteria', models.JSONField(blank=True, help_text="Conditional targeting (e.g., {'min_level': 5})", null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='If null, this is a broadcast to all users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Notification',
                'verbose_name_plural': 'Site Notifications',
                'db_table': 'core_site_notifications',
            },
        ),
    ]
