import type { NexusEventWithOrganizer } from "@/types/database";

const future = (days: number) =>
  new Date(Date.now() + days * 86400000).toISOString();
const past = (days: number) =>
  new Date(Date.now() - days * 86400000).toISOString();

export const SAMPLE_EVENTS: NexusEventWithOrganizer[] = [
  {
    id: "00000000-0000-4000-8000-000000000101",
    organizer_id: null,
    title: "Nexus Creator Summit 2026",
    description:
      "国内外のクリエイターが集う年次サミット。基調講演・ポートフォリオレビュー・ネットワーキング。",
    category: "meetup",
    format: "hybrid",
    status: "published",
    starts_at: future(14),
    ends_at: future(14),
    venue_name: "Eldonia Hall Tokyo",
    venue_address: "東京都渋谷区（詳細は購入後に表示）",
    online_url: "https://example.com/stream",
    cover_image_url: null,
    ticket_price: 4500,
    compare_price: 5500,
    capacity: 200,
    tickets_sold: 87,
    is_featured: true,
    is_nexus_verified: true,
    tags: ["サミット", "ネットワーキング"],
    created_at: past(30),
    updated_at: past(1),
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000102",
    organizer_id: null,
    title: "Golden Ink Live — Digital Art Session",
    description:
      "ライブデジタルペイント配信。チャット参加・限定ブラシ配布あり。",
    category: "streaming",
    format: "online",
    status: "published",
    starts_at: future(3),
    ends_at: future(3),
    venue_name: null,
    venue_address: null,
    online_url: "https://example.com/live",
    cover_image_url: null,
    ticket_price: 1500,
    compare_price: null,
    capacity: 500,
    tickets_sold: 312,
    is_featured: true,
    is_nexus_verified: true,
    tags: ["配信", "ライブ", "イラスト"],
    created_at: past(20),
    updated_at: past(2),
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000103",
    organizer_id: null,
    title: "Fantasy Orchestra Night",
    description:
      "ゲーム・ファンタジー系楽曲のオーケストラコンサート。VIP席あり。",
    category: "concert",
    format: "offline",
    status: "published",
    starts_at: future(30),
    ends_at: future(30),
    venue_name: "Realm Concert Hall",
    venue_address: "大阪府大阪市北区",
    online_url: null,
    cover_image_url: null,
    ticket_price: 6800,
    compare_price: 7800,
    capacity: 120,
    tickets_sold: 45,
    is_featured: false,
    is_nexus_verified: true,
    tags: ["コンサート", "音楽"],
    created_at: past(15),
    updated_at: past(3),
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000104",
    organizer_id: null,
    title: "Worldbuilding Workshop — Lore & Maps",
    description: "世界観設計・地図制作の実践ワークショップ。少人数制。",
    category: "workshop",
    format: "offline",
    status: "published",
    starts_at: future(7),
    ends_at: future(7),
    venue_name: "Creator Studio Shibuya",
    venue_address: "東京都渋谷区",
    online_url: null,
    cover_image_url: null,
    ticket_price: 3200,
    compare_price: null,
    capacity: 24,
    tickets_sold: 18,
    is_featured: false,
    is_nexus_verified: false,
    tags: ["ワークショップ", "設定"],
    created_at: past(10),
    updated_at: past(1),
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000105",
    organizer_id: null,
    title: "Indie Game Showcase & Pitch",
    description:
      "インディーゲーム展示とピッチコンテスト。審査員フィードバック付き。",
    category: "competition",
    format: "hybrid",
    status: "published",
    starts_at: future(21),
    ends_at: future(21),
    venue_name: "Nexus Expo Center",
    venue_address: "オンライン同時配信",
    online_url: "https://example.com/expo",
    cover_image_url: null,
    ticket_price: 0,
    compare_price: null,
    capacity: 300,
    tickets_sold: 156,
    is_featured: true,
    is_nexus_verified: false,
    tags: ["ゲーム", "コンテスト", "無料"],
    created_at: past(8),
    updated_at: past(1),
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000106",
    organizer_id: null,
    title: "Gallery Night — Creator Exhibition",
    description: "GALLEY 出品作家による期間限定展示。入場無料・作品即売あり。",
    category: "exhibition",
    format: "offline",
    status: "published",
    starts_at: past(2),
    ends_at: future(5),
    venue_name: "Eldonia Gallery Space",
    venue_address: "東京都目黒区",
    online_url: null,
    cover_image_url: null,
    ticket_price: 0,
    compare_price: null,
    capacity: null,
    tickets_sold: 890,
    is_featured: false,
    is_nexus_verified: true,
    tags: ["展示", "無料"],
    created_at: past(14),
    updated_at: past(1),
    profiles: null,
  },
];
