# Generated by Django 4.2.30 on 2026-07-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='表示名')),
                ('role_ja', models.CharField(max_length=120, verbose_name='役割（日本語）')),
                ('role_en', models.CharField(blank=True, max_length=120, verbose_name='役割（英語）')),
                ('role_ko', models.CharField(blank=True, max_length=120, verbose_name='役割（韓国語）')),
                ('role_zh_cn', models.CharField(blank=True, max_length=120, verbose_name='役割（中国語・簡体）')),
                ('url', models.URLField(blank=True, verbose_name='リンク URL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'フッター協力・スポンサー',
                'verbose_name_plural': 'フッター協力・スポンサー',
                'db_table': 'footer_partners',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
