# Generated by Django 4.2.30 on 2026-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_seed_footer_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpartner',
            name='link_enabled',
            field=models.BooleanField(default=False, help_text='オンのときのみ、下の URL をフッターでクリック可能にします。', verbose_name='リンク付き'),
        ),
        migrations.AlterField(
            model_name='footerpartner',
            name='url',
            field=models.URLField(blank=True, help_text='「リンク付き」がオンのとき必須。オフなら保存していても表示しません。', verbose_name='リンク URL'),
        ),
    ]
