import type { JobListingWithPoster, Portfolio } from "@/types/database";

const now = new Date().toISOString();

export const SAMPLE_JOBS: JobListingWithPoster[] = [
  {
    id: "00000000-0000-4000-8000-000000000401",
    poster_id: null,
    title: "ファンタジーBGMコンポーザー（短期）",
    description:
      "TRPG用 BGM 5 曲。ダークファンタジー調。リファレンス共有あり。",
    job_type: "freelance",
    location: "リモート",
    budget_min: 80000,
    budget_max: 150000,
    skills_required: ["作曲", "DAW", "オーケストラ"],
    status: "open",
    is_featured: true,
    created_at: now,
    updated_at: now,
    profiles: { display_name: "Game Studio Alpha", username: "studio_alpha" },
  },
  {
    id: "00000000-0000-4000-8000-000000000402",
    poster_id: null,
    title: "キャラクターデザイナー（協業）",
    description: "インディーゲームの主要キャラ 3 体。世界観資料あり。",
    job_type: "collab",
    location: "ハイブリッド",
    budget_min: null,
    budget_max: null,
    skills_required: ["イラスト", "キャラデザ", "Blender"],
    status: "open",
    is_featured: true,
    created_at: now,
    updated_at: now,
    profiles: { display_name: "Indie Forge", username: "indie_forge" },
  },
  {
    id: "00000000-0000-4000-8000-000000000403",
    poster_id: null,
    title: "ライブ2Dモデラー",
    description: "VTuber 向け Live2D モデル制作。分割納品可。",
    job_type: "freelance",
    location: "リモート",
    budget_min: 200000,
    budget_max: 350000,
    skills_required: ["Live2D", "Illustrator"],
    status: "open",
    is_featured: false,
    created_at: now,
    updated_at: now,
    profiles: { display_name: "Stream Nexus", username: "stream_nexus" },
  },
  {
    id: "00000000-0000-4000-8000-000000000404",
    poster_id: null,
    title: "コミュニティモデレーター（パート）",
    description: "Discord / 掲示板のモデレーション。日本語・英語。",
    job_type: "part_time",
    location: "リモート",
    budget_min: 1500,
    budget_max: 2000,
    skills_required: ["モデレーション", "英語"],
    status: "open",
    is_featured: false,
    created_at: now,
    updated_at: now,
    profiles: { display_name: "Eldonia Ops", username: "eldonia_ops" },
  },
];

export const SAMPLE_PORTFOLIO: Portfolio = {
  id: "00000000-0000-4000-8000-000000000501",
  user_id: "demo-user",
  headline: "Dark Fantasy Illustrator",
  summary: "TRPG・ゲーム向けイラスト。Gold & Obsidian テイスト。",
  skills: ["イラスト", "Live2D", "Blender"],
  exp_points: 2400,
  level: 5,
  title_badge: "Nexus Artisan",
  visibility: "public",
  attach_on_apply: true,
  created_at: now,
  updated_at: now,
};
