# Generated by Django 5.2.3 on 2025-12-13 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text="ISO 4217 currency code (e.g., 'JPY', 'USD', 'KRW')", max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Currency name (e.g., 'Japanese Yen')", max_length=100)),
                ('symbol', models.CharField(help_text="Currency symbol (e.g., '¥')", max_length=10)),
                ('decimal_places', models.IntegerField(default=0, help_text='Number of decimal places (e.g., 0 for JPY, 2 for USD)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(help_text="ISO 639-1 language code (e.g., 'ja', 'en', 'ko')", max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Language name in English (e.g., 'Japanese')", max_length=100)),
                ('native_name', models.CharField(help_text="Language name in native script (e.g., '日本語')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=8, help_text='Exchange rate (1 from_currency = rate * to_currency)', max_digits=20)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this rate became effective')),
                ('source', models.CharField(blank=True, help_text="Source of the exchange rate (e.g., 'ECB', 'manual')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_currency', models.ForeignKey(db_column='from_currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='localization.currency')),
                ('to_currency', models.ForeignKey(db_column='to_currency_code', on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='localization.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'db_table': 'exchange_rates',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', '-effective_date'], name='exchange_ra_from_cu_34f4b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('artwork', 'Artwork'), ('event', 'Event'), ('product', 'Product'), ('post', 'Post'), ('comment', 'Comment')], max_length=50)),
                ('content_id', models.BigIntegerField(help_text='ID of the content being translated')),
                ('field_name', models.CharField(help_text="Field name (e.g., 'title', 'description')", max_length=100)),
                ('translation', models.TextField(help_text='Translated text')),
                ('is_machine_translated', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.language')),
            ],
            options={
                'verbose_name': 'Content Translation',
                'verbose_name_plural': 'Content Translations',
                'db_table': 'content_translations',
                'indexes': [models.Index(fields=['content_type', 'content_id'], name='content_tra_content_f33fc0_idx'), models.Index(fields=['language'], name='content_tra_languag_2695ef_idx')],
                'unique_together': {('content_type', 'content_id', 'field_name', 'language')},
            },
        ),
    ]
