import type { ShopProductWithSeller } from "@/types/database";

const now = "2026-01-01T00:00:00.000Z";

/** DB 未適用時のデモ商品（固定 UUID） */
export const SAMPLE_PRODUCTS: ShopProductWithSeller[] = [
  {
    id: "00000000-0000-4000-8000-000000000001",
    seller_id: null,
    title: "Eldonia Crest Hoodie — Obsidian",
    description:
      "漆黒地に金のエンブレムを配した公式パーカー。創作の合間に纏う、Nexus 定番アイテム。",
    category: "apparel",
    product_type: "physical",
    price: 8800,
    compare_at_price: 11000,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.7,
    review_count: 128,
    stock_quantity: 42,
    is_nexus_prime: true,
    is_nexus_choice: true,
    is_bestseller: true,
    is_active: true,
    tags: ["公式", "アパレル", "限定"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000002",
    seller_id: null,
    title: "Digital Brush Pack Vol. I — Golden Ink",
    description:
      "ファンタジー描線向け Procreate / Photoshop ブラシ 48 本。金箔・古羊皮紙テクスチャ付き。",
    category: "digital",
    product_type: "digital",
    price: 2400,
    compare_at_price: null,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.9,
    review_count: 312,
    stock_quantity: null,
    is_nexus_prime: true,
    is_nexus_choice: true,
    is_bestseller: true,
    is_active: true,
    tags: ["デジタル", "ブラシ", "イラスト"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000003",
    seller_id: null,
    title: "Artisan Desk Mat — Realm Map",
    description: "王国全图をあしらった超大判デスクマット。防水・滑り止め加工。",
    category: "goods",
    product_type: "physical",
    price: 4500,
    compare_at_price: 5200,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.5,
    review_count: 89,
    stock_quantity: 18,
    is_nexus_prime: false,
    is_nexus_choice: false,
    is_bestseller: false,
    is_active: true,
    tags: ["グッズ", "デスク"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000004",
    seller_id: null,
    title: "Nexus Prime Annual Scroll",
    description:
      "Nexus Prime 年間メンバーシップ。送料無料・限定セール早期アクセス・デジタル特典。",
    category: "digital",
    product_type: "digital",
    price: 9800,
    compare_at_price: null,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.8,
    review_count: 56,
    stock_quantity: null,
    is_nexus_prime: true,
    is_nexus_choice: false,
    is_bestseller: false,
    is_active: true,
    tags: ["メンバーシップ", "Prime"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    seller_id: null,
    title: "Lore Compendium PDF Bundle",
    description: "世界観設定資料・キャラクター档案・魔法体系ガイドの PDF 3 冊セット。",
    category: "books",
    product_type: "digital",
    price: 1800,
    compare_at_price: 2200,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.6,
    review_count: 44,
    stock_quantity: null,
    is_nexus_prime: true,
    is_nexus_choice: false,
    is_bestseller: false,
    is_active: true,
    tags: ["PDF", "設定資料"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    seller_id: null,
    title: "Creator Toolkit — Sound FX Chest",
    description: "環境音・魔法効果音 120 点。ゲーム・動画・配信向けロイヤリティフリー。",
    category: "tools",
    product_type: "digital",
    price: 3200,
    compare_at_price: null,
    image_url: null,
    download_url: null,
    gallery_urls: [],
    rating: 4.4,
    review_count: 67,
    stock_quantity: null,
    is_nexus_prime: false,
    is_nexus_choice: true,
    is_bestseller: false,
    is_active: true,
    tags: ["音声", "SFX", "クリエイター"],
    created_at: now,
    updated_at: now,
    profiles: null,
  },
];
