# Generated by Django 5.1.3 on 2025-11-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_add_orderid_to_referraltrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referraltrack',
            name='order_id',
        ),
    ]
