# Generated by Django 5.1.3 on 2025-11-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_remove_referraltrack_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='referraltrack',
            name='order_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
