# Generated by Django 5.2.3 on 2025-12-14 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_add_creator_denorm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(choices=[('illustration', 'イラスト'), ('manga', '漫画'), ('animation', 'アニメーション'), ('3d', '3Dモデル'), ('music', '音楽'), ('video', '動画'), ('novel', '小説'), ('game', 'ゲーム'), ('design', 'デザイン'), ('photo', '写真'), ('other', 'その他')], default='illustration', max_length=50)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('file_urls', models.JSONField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('tools_used', models.JSONField(blank=True, null=True)),
                ('creation_period', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('visibility', models.CharField(choices=[('public', '公開'), ('unlisted', '限定公開'), ('private', '非公開')], default='public', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='marketplace.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['-is_featured', 'sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='marketplace.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio_likes',
            },
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', 'visibility'], name='portfolios_user_id_6292fb_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['work_type'], name='portfolios_work_ty_d5148a_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['-created_at'], name='portfolios_created_3863d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliolike',
            unique_together={('user', 'portfolio')},
        ),
    ]
