# Generated by Django 5.1.3 on 2026-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_referral_country_rebate_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='supabase_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Supabase public.artworks.id', null=True, unique=True),
        ),
    ]
