# Generated by Django 4.2.30 on 2026-07-13 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0010_artwork_gallery_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品（旧）', 'verbose_name_plural': '商品（旧）'},
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_id', models.UUIDField(db_index=True, editable=False, help_text='Supabase public.shop_products.id', unique=True)),
                ('seller_external_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, default='goods', max_length=50)),
                ('product_type', models.CharField(choices=[('physical', 'physical'), ('digital', 'digital')], db_index=True, default='physical', max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('compare_at_price', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('download_url', models.URLField(blank=True, max_length=1000)),
                ('source_artwork_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('gallery_urls', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('stock_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('is_nexus_prime', models.BooleanField(default=False)),
                ('is_nexus_choice', models.BooleanField(default=False)),
                ('is_bestseller', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SHOP商品',
                'verbose_name_plural': 'SHOP商品',
                'db_table': 'shop_products_mirror',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='shop_produc_is_acti_371f54_idx'), models.Index(fields=['category', 'is_active'], name='shop_produc_categor_f466eb_idx')],
            },
        ),
    ]
