# Generated by Django 5.1.3 on 2025-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_user_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(default='free', max_length=20),
        ),
    ]
