# Generated by Django 5.1.3 on 2025-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_alter_user_subscription_plan'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_plan'], name='users_subscri_95bd21_idx'),
        ),
    ]
