# Generated by Django 5.1.3 on 2025-11-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_add_referred_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription'], name='users_subscri_f90c0b_idx'),
        ),
    ]
