# Generated by Django 5.2.3 on 2025-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0009_user_users_subscri_f90c0b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='JPY', help_text="User's preferred currency (ISO 4217 code)", max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='ja', help_text="User's preferred language (ISO 639-1 code)", max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Tokyo', help_text="User's timezone (e.g., 'Asia/Tokyo', 'America/New_York')", max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['preferred_language'], name='users_preferr_cf0f22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['preferred_currency'], name='users_preferr_8f3f2c_idx'),
        ),
    ]
