# Generated by Django 5.2.3 on 2025-12-14 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_preferred_currency_user_preferred_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_kana', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name_kana', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_position', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('education_status', models.CharField(blank=True, max_length=50, null=True)),
                ('income_range', models.CharField(blank=True, choices=[('under_200', 'Under 2M JPY'), ('200_400', '2M - 4M JPY'), ('400_600', '4M - 6M JPY'), ('600_800', '6M - 8M JPY'), ('800_1000', '8M - 10M JPY'), ('over_1000', 'Over 10M JPY'), ('undisclosed', 'Undisclosed')], max_length=20, null=True)),
                ('interests', models.JSONField(blank=True, null=True)),
                ('self_introduction', models.TextField(blank=True, null=True)),
                ('desired_work_types', models.JSONField(blank=True, null=True)),
                ('desired_hourly_rate_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('desired_hourly_rate_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_hours_per_week', models.IntegerField(blank=True, null=True)),
                ('is_remote_available', models.BooleanField(blank=True, null=True)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('has_signed_nda', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address_type', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('billing', 'Billing'), ('shipping', 'Shipping')], default='home', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_addresses',
                'indexes': [models.Index(fields=['country_code'], name='user_addres_country_e47441_idx'), models.Index(fields=['postal_code'], name='user_addres_postal__3b9b12_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('art', 'Art & Illustration'), ('music', 'Music & Audio'), ('video', 'Video & Animation'), ('writing', 'Writing & Content'), ('programming', 'Programming'), ('design', 'Design'), ('3d', '3D Modeling'), ('game', 'Game Development'), ('marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=50)),
                ('level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_skills',
                'ordering': ['-is_primary', 'sort_order', '-level'],
                'indexes': [models.Index(fields=['skill_name'], name='user_skills_skill_n_caf71e_idx'), models.Index(fields=['category'], name='user_skills_categor_043040_idx')],
            },
        ),
    ]
